#!/usr/bin/env python3


"""
@file     ubuntufetch
@date     20/07/2023
@version  1.0
@license  GNU General Public License v2.0
@url      github.com/Julynx/ubuntufetch
@author   Julynx
"""


from subprocess import Popen, PIPE

RED = "\033[1;31m"
GREEN = "\033[1;32m"
YELLOW = "\033[1;33m"
BLUE = "\033[1;34m"
MAGENTA = "\033[1;35m"
CYAN = "\033[1;36m"
RESET = "\033[0;0m"


def get_distro():
    c_distro = """$(hostnamectl | grep "Operating System" | awk '{print($3 " " $4 " " $5)}')"""
    subprocess2 = Popen("echo " + c_distro, shell=True, stdout=PIPE)
    return subprocess2.stdout.read().decode('utf-8').strip()


def get_session():
    c_display_server = "echo $DESKTOP_SESSION"
    subprocess9 = Popen(c_display_server, shell=True, stdout=PIPE)
    return subprocess9.stdout.read().decode('utf-8').strip().capitalize()


def get_kernel():
    c_kernel = "$(uname -r)"
    subprocess3 = Popen("echo " + c_kernel, shell=True, stdout=PIPE)
    return subprocess3.stdout.read().decode('utf-8').strip()


def get_uptime():
    c_uptime = "$(uptime -p | cut -c 4-)"
    subprocess5 = Popen("echo " + c_uptime, shell=True, stdout=PIPE)
    return subprocess5.stdout.read().decode('utf-8').strip()


def get_memory():
    c_memory = """$(free | grep Mem | awk '{printf("%.1f", $3/1000000)}')GB of $(free -m| grep Mem | awk '{printf("%d", ($2/1000)+1)}')GB used"""
    subprocess7 = Popen("echo " + c_memory, shell=True, stdout=PIPE)
    return subprocess7.stdout.read().decode('utf-8').strip()


def get_battery():
    c_battery = "upower -i /org/freedesktop/UPower/devices/battery_BAT0 | grep -i 'state\|percentage' | awk '{print($2)}' | tac | tr '\n' ' '"
    subprocess8 = Popen(c_battery, shell=True, stdout=PIPE)
    return subprocess8.stdout.read().decode('utf-8').strip()


rows = 2
separator, block = " ", "████"
colors = rows * (f"{RED}{block}{separator}"
                 f"{GREEN}{block}{separator}"
                 f"{YELLOW}{block}{separator}"
                 f"{BLUE}{block}{separator}"
                 f"{MAGENTA}{block}{separator}"
                 f"{CYAN}{block}{separator}"
                 f"{RESET}\n")

data = (f"{YELLOW}Distro     {RESET}{get_distro()}\n"
        f"{YELLOW}Session    {RESET}{get_session()}\n"
        f"{YELLOW}Kernel     {RESET}{get_kernel()}\n"
        f"{YELLOW}Uptime     {RESET}{get_uptime()}\n"
        f"{YELLOW}Memory     {RESET}{get_memory()}\n"
        f"{YELLOW}Battery    {RESET}{get_battery()}\n"
        "\n"
        f"{colors}")

print(data)
